name: publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: publish to hey.prose.sh
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -v
        path: imgs/* *.md
        remote_path: /
        remote_user: hey
        remote_host: prose.sh
        remote_key: ${{ secrets.PRIVATE_KEY }}
    - name: publish to pico.prose.sh
      uses: burnett01/rsync-deployments@6.0.0
      with:
        switches: -v
        path: imgs/* *.md
        remote_path: /
        remote_user: pico
        remote_host: prose.sh
        remote_key: ${{ secrets.PICO_PRIVATE_KEY }}
